version: '2'
services:
  db:
    container_name: db
    build: "./db"
    volumes:
      - "./db/data:/docker-entrypoint-initdb.d/"   # SQL files here get executed when the container first starts

  api:
    container_name: api
    build: "./api"
    volumes:
      - ./api:/code
    depends_on:
      - db

  jupyter:
    container_name: jupyter
    build: "./api"   # Same Dockerfile as api so we've got access to django models
    ports:
      - "8888:8888"  # Expose directly. Websockets do not play nicely with nginx proxy_pass
    volumes:
      - .:/code
    command: "python3 api/manage.py shell_plus --notebook"
    depends_on:
      - db

  elm:
    container_name: elm
    build: "./elm"
    volumes:
      - ./web:/code
    depends_on:
      - api

  www:
    container_name: www
    build: "./web"
    ports:
      - "80:80"
    volumes:
      - ./web/static:/usr/share/nginx/html
      - ./web/conf:/etc/nginx




