version: '2'
services:
  black-formatter:
    # Python code formatting
    build:
      context: tools
      dockerfile: black.Dockerfile
    # Show it our python code
    volumes:
      - ./api:/code
    # and format all our python code by default
    entrypoint:
      - "black"
      - "."


  ts-compile:
    container_name: ts-compile
    build: "./ts"    # Same Dockerfile as javascript so we've got access to node
    volumes:
      - ./ts:/code
    command: "npm run watch"  # Sit there and watch it go
