version: '2'
services:
  black-formatter:
    # Python code formatting
    build:
      context: tools
      dockerfile: black.Dockerfile
    volumes:
      - ./api:/code
    entrypoint:
      - "black"
      - "."

  manage:
    # Run the Django management command
    build:
      context: ./api
    volumes:
      - ./api:/code
    entrypoint:
      - "python"
      - "manage.py"
