version: '2'
services:
  black-formatter:
    # Python code formatting
    build:
      context: tools
      dockerfile: black.Dockerfile
    # Show it our python code
    volumes:
      - ./api:/code
    # and format all our python code by default
    entrypoint:
      - "black"
      - "."

  jupyter:
    container_name: jupyter
    build: "./api"   # Same Dockerfile as api so we've got access to django models
    ports:
      - "8888:8888"  # Expose directly. Websockets do not play nicely with nginx proxy_pass
    volumes:
      - .:/code
    command: "python3 api/manage.py shell_plus --notebook"

  ts-compile:
    container_name: ts-compile
    build: "./ts"    # Same Dockerfile as javascript so we've got access to node
    volumes:
      - ./ts:/code
    command: "npm run watch"  # Sit there and watch it go
