version: '3'
services:
  db:
    build: "./db"
    volumes:
      # SQL files here get executed when the container first starts
      - "./db/data:/docker-entrypoint-initdb.d/"

  api:
    build: "./api"
    volumes:
      - ./api:/code
      - ./api/static:/static
    restart: always
    depends_on:
      - db
    ports:
      - "8000:8000"
    command: "python manage.py runserver_plus 0.0.0.0:8000"

  jupyter:
    container_name: jupyter
    build: "./api"
    ports:
      - "8888:8888"  # Expose directly. Websockets do not play nicely with nginx proxy_pass
    volumes:
      - .:/code
    command: "python3 api/manage.py shell_plus --notebook"
    depends_on:
      - db

  ts:
    build: "./ts"
    ports:
      - 3000:3000
    volumes:
      - ./ts/dist:/code/dist
      - ./ts/src:/code/src
      - ./ts/public:/code/public

  web:
    build: "./web"
    ports:
      - "80:80"
    volumes:
      - ./ts/dist:/usr/share/nginx/ts          # Shared volume for compiled code
      - ./web/static:/usr/share/nginx/static
      - ./web/conf:/etc/nginx
    depends_on:
      - api
      - db
      - ts







