version: '3'
services:
  db:
    build: "./db"
    ports:
      - "5432:5432"

  migrate:
    build: "./api"
    command: "python3 ./digmaps/manage.py migrate"
    depends_on:
      - db

  api:
    build: "./api"
    ports:
      - "8080:8080"   # Main application port
      - "8000:8000"   # Secondary debugging port (nothing runs here by default)
    working_dir: /code
    volumes:
      - ./api:/code
    depends_on:
      - db
      - migrate

  web:
    build: "./web"
    ports:
      - "8001:8001"
    working_dir: /code
    volumes:
      - ./web:/code
    depends_on:
      - db
      - api

  jupyter:
    build: "./api"
    ports:
      - "8888:8888"
    working_dir: /code
    volumes:
      - .:/code
    command: "python3 ./manage.py shell_plus --notebook"
    depends_on:
      - db
      - api





