version: '3'
services:
  db:
    build: "./db"
    ports:
      - "5432:5432"
    volumes:
      - "./db/data:/docker-entrypoint-initdb.d/"

  migrate:
    build: "./api"
    command: "python3 manage.py migrate"
    volumes:
      - ./api:/code
    depends_on:
      - db

  api:
    build: "./api"
    ports:
      - "8080:8080"   # Main application port
      - "8000:8000"   # Secondary debugging port (nothing runs here by default)
    volumes:
      - ./api:/code
    depends_on:
      - db
      - migrate

  elm:
    build: "./elm"
    ports:
      - "8001:8001"
    volumes:
      - ./web:/code
    depends_on:
      - api

  web:
    build: "./web"
    ports:
      - "80:80"
    volumes:
      - ./web/static:/usr/share/nginx/html
      - ./web/conf:/etc/nginx

  jupyter:
    build: "./api"
    ports:
      - "8888:8888"
    volumes:
      - .:/code
    command: "python3 api/manage.py shell_plus --notebook"
    depends_on:
      - db
      - api





