version: '3'
services:
  db:
    build: "./db"
    ports:
      - "5432:5432"  # Exposed outside dockerland so we can connect a workbench
    volumes:
      - "./db/data:/docker-entrypoint-initdb.d/"

  migrate:
    # One-shot service to run DB migrations before we start the API service
    build: "./api"
    command: "python3 manage.py migrate"
    volumes:
      - ./api:/code
    depends_on:
      - db

  api:
    build: "./api"
    ports:
      - "80"          # Main application port, forwarding handled by nginx
      - "8000:8000"   # Secondary debugging port exposed outside dockerland
    volumes:
      - ./api:/code
    depends_on:
      - db
      - migrate

  jupyter:
    # Same Dockerfile api so we've got access to django models
    build: "./api"
    ports:
      - "80"  # Only directly to other containers; exposed by nginx
    # Has access to the whole project's files.
    volumes:
      - .:/code
    # Different command than the standard one in the Dockerfile
    command: "python3 api/manage.py shell_plus --notebook"
    depends_on:
      - db
      - api

  elm:
    build: "./elm"
    ports:
      - "80"  # Only directly to other containers; exposed by nginx
    volumes:
      - ./web:/code
    depends_on:
      - api

  www:
    build: "./web"
    ports:
      - "80"  # Only directly to other containers; exposed by nginx
    volumes:
      - ./web/static:/usr/share/nginx/html
      - ./web/conf:/etc/nginx






