version: '3'
services:
  db:
    build: "./db"
    volumes:
      - "./db/data:/docker-entrypoint-initdb.d/"   # SQL files here get executed when the container first starts

  api:
    build: "./api"
    volumes:
      - ./api:/code
      - ./api/static:/static
    depends_on:
      - db
    ports:
      - "8000:8000"
    command: "python manage.py runserver_plus 0.0.0.0:8000"

  ts:
    build: "./ts"
    ports:
      - 3000:3000
    volumes:
      - ./ts/dist:/code/dist
      - ./ts/src:/code/src
    command: "npm start"
    depends_on:
      - ts-compile

  ts-compile:
    build: "./ts"
    volumes:
      - ./ts/dist:/code/dist
      - ./ts/src:/code/src
    command: "npm run watch"

  web:
    build: "./web"
    ports:
      - "80:80"
    volumes:
      - ./ts/dist:/usr/share/nginx/ts          # Shared volume for compiled code
      - ./web/static:/usr/share/nginx/static
      - ./web/conf:/etc/nginx
    depends_on:
      - api
      - db
      - ts






