version: '2'
services:
  db:
    container_name: db
    build: "./db"
    volumes:
      - "./db/data:/docker-entrypoint-initdb.d/"   # SQL files here get executed when the container first starts

  api:
    container_name: api
    build: "./api"
    volumes:
      - ./api:/code
    depends_on:
      - db
    ports:
      - "8000:8000"
    command: "python manage.py runserver_plus 0.0.0.0:8000"

  www:
    container_name: www
    build: "./web"
    ports:
      - "80:80"
    volumes:
      - ./web/static:/usr/share/nginx/html
      - ./web/conf:/etc/nginx




