# onbuild docker image automatically runs pip install on requirements.txt
FROM python:3

# Additional utilities
RUN apt-get update && apt-get install -y \
    postgresql-client \
    binutils \
    libproj-dev \
    gdal-bin \
    postgresql-server-dev-all

# Pip last, since these things change so frequently
COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

